// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Endpoint raíz para comprobar el estado de la API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Muestra mensaje de bienvenida",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/productos": {
            "get": {
                "description": "Obtiene listado paginado y filtrado de productos con datos técnicos de scraping para Superadmin",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Catálogo de productos para administración",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Búsqueda por texto libre",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Número de página (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Cantidad de productos por página (default: 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por categoría",
                        "name": "categoria",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por supermercado o cadena",
                        "name": "supermercado",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por marca",
                        "name": "marca",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por SKU",
                        "name": "sku",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar por disponibilidad de stock",
                        "name": "en_stock",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Precio mínimo",
                        "name": "precio_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Precio máximo",
                        "name": "precio_max",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar solo productos en oferta",
                        "name": "en_oferta",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Criterio de ordenamiento (precio, nombre, marca, sku, fecha)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Dirección del orden (asc, desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PaginaProductosAdminDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/google": {
            "post": {
                "description": "Valida el token de Google y aplica lógica find-or-create para la cuenta de usuario",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Inicio de sesión con Google",
                "parameters": [
                    {
                        "description": "Token JWT de Google",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GoogleLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Verifica credenciales de acceso, valida cuenta activa y emite token JWT firmado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Inicio de sesión local de usuario",
                "parameters": [
                    {
                        "description": "Credenciales de acceso",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "description": "Endpoint protegido para verificar identidad y claims extraídos del token JWT",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Perfil del usuario autenticado",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    }
                }
            },
            "put": {
                "description": "Permite al usuario autenticado actualizar su nombre, correo, teléfono, dirección o contraseña. El ID se extrae directamente del token JWT (prevención IDOR).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Actualización parcial del perfil de usuario",
                "parameters": [
                    {
                        "description": "Campos a actualizar",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ActualizarPerfilDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PerfilUsuarioDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Valida complejidad de contraseña, encripta con bcrypt, crea usuario y genera automáticamente cookie HttpOnly para inicio de sesión inmediato",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registrar nuevo usuario con auto-login",
                "parameters": [
                    {
                        "description": "Datos de registro",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegistroRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.RegistroResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.RespuestaError"
                        }
                    }
                }
            }
        },
        "/api/v1/productos": {
            "get": {
                "description": "Obtiene una lista paginada de productos con soporte para múltiples filtros (categoría, supermercado, marca, rango de precio, en oferta) y ordenamiento.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "productos"
                ],
                "summary": "Catálogo y filtrado de productos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Búsqueda por texto libre",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Número de página (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Cantidad de productos por página (default: 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por categoría",
                        "name": "categoria",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por supermercado o cadena",
                        "name": "supermercado",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por marca",
                        "name": "marca",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Precio mínimo",
                        "name": "precio_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Precio máximo",
                        "name": "precio_max",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar solo productos en oferta",
                        "name": "en_oferta",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Criterio de ordenamiento (precio, nombre, marca)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Dirección del orden (asc, desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PaginaProductosDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/productos/buscar": {
            "get": {
                "description": "Busca productos que coincidan parcialmente en título, marca o categoría con el parámetro 'q' (mínimo 3 caracteres obligatorios).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "productos"
                ],
                "summary": "Búsqueda de productos por término",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Término de búsqueda (mínimo 3 caracteres)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Número de página (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Cantidad de productos por página (default: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PaginaProductosDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/productos/{id}": {
            "get": {
                "description": "Obtiene la información completa de un producto por su ID junto con el historial de precios capturados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "productos"
                ],
                "summary": "Consulta detalle de producto y su historial de precios",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del producto (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ProductoDetalleDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/scraper/productos": {
            "post": {
                "description": "Guarda productos crudos y capturas de precio sin requerir una sesión de trabajo previa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraper"
                ],
                "summary": "Almacena un lote de productos de forma directa",
                "parameters": [
                    {
                        "description": "Lote de productos extraídos",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.IngestaLoteDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.IngestaResultadoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/scraper/trabajos": {
            "post": {
                "description": "Registra el inicio de una araña de scraping para auditar su ciclo de vida y métricas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraper"
                ],
                "summary": "Inicia una sesión de scraping",
                "parameters": [
                    {
                        "description": "Datos de inicio de la sesión",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.IniciarTrabajoDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.TrabajoScraperDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/scraper/trabajos/{id}": {
            "get": {
                "description": "Retorna los detalles, duración, conteo y errores de un trabajo (ideal para bots de Discord)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraper"
                ],
                "summary": "Consulta el estado de una sesión de scraping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del trabajo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TrabajoScraperDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/scraper/trabajos/{id}/ejecutar": {
            "post": {
                "description": "Envía el trabajo a Redis para que el worker Scrapy ejecute el spider solicitado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraper"
                ],
                "summary": "Encola un trabajo para ejecución",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del trabajo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Spider y parámetros opcionales",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ejecutarScraperRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/scraper/trabajos/{id}/finalizar": {
            "put": {
                "description": "Marca el término del trabajo como completado o fallido, registrando métricas y errores",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraper"
                ],
                "summary": "Finaliza una sesión de scraping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del trabajo de scraping",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de cierre de la sesión",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.FinalizarTrabajoDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TrabajoScraperDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/scraper/trabajos/{id}/productos": {
            "post": {
                "description": "Realiza el upsert de productos crudos y guarda sus capturas de precios vinculados a una sesión",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scraper"
                ],
                "summary": "Almacena un lote de productos asociado a un trabajo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del trabajo de scraping",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lote de productos extraídos",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.IngestaLoteDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.IngestaResultadoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ActualizarPerfilDTO": {
            "type": "object",
            "properties": {
                "correo": {
                    "type": "string"
                },
                "direccion": {
                    "type": "string"
                },
                "nombre_completo": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "telefono": {
                    "type": "string"
                }
            }
        },
        "domain.FinalizarTrabajoDTO": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "elementos_extraidos": {
                    "type": "integer"
                },
                "estado": {
                    "description": "'completado' o 'fallido'",
                    "type": "string"
                },
                "registro_errores": {
                    "type": "string"
                }
            }
        },
        "domain.HistorialPrecioDTO": {
            "type": "object",
            "properties": {
                "capturado_el": {
                    "type": "string"
                },
                "precio_normal": {
                    "type": "number"
                },
                "precio_oferta": {
                    "type": "number"
                }
            }
        },
        "domain.IngestaLoteDTO": {
            "type": "object",
            "required": [
                "productos"
            ],
            "properties": {
                "codigo_sucursal": {
                    "type": "string"
                },
                "productos": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.ProductoScrapeadoDTO"
                    }
                },
                "sucursal_id": {
                    "type": "integer"
                },
                "supermercado": {
                    "type": "string"
                }
            }
        },
        "domain.IngestaResultadoDTO": {
            "type": "object",
            "properties": {
                "actualizados": {
                    "type": "integer"
                },
                "errores": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "insertados": {
                    "type": "integer"
                },
                "mensaje": {
                    "type": "string"
                },
                "precios_registrados": {
                    "type": "integer"
                },
                "sucursal_id": {
                    "type": "integer"
                },
                "total_recibidos": {
                    "type": "integer"
                },
                "trabajo_id": {
                    "type": "string"
                }
            }
        },
        "domain.IniciarTrabajoDTO": {
            "type": "object",
            "required": [
                "cadena_id"
            ],
            "properties": {
                "cadena_id": {
                    "type": "integer"
                },
                "disparado_por_usuario_id": {
                    "type": "string"
                },
                "supermercado": {
                    "type": "string"
                }
            }
        },
        "domain.MetadatosPaginacionDTO": {
            "type": "object",
            "properties": {
                "limite": {
                    "type": "integer"
                },
                "pagina_actual": {
                    "type": "integer"
                },
                "total_paginas": {
                    "type": "integer"
                },
                "total_registros": {
                    "type": "integer"
                }
            }
        },
        "domain.PaginaProductosAdminDTO": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductoAdminDTO"
                    }
                },
                "limite": {
                    "type": "integer"
                },
                "pagina_actual": {
                    "type": "integer"
                },
                "paginacion": {
                    "$ref": "#/definitions/domain.MetadatosPaginacionDTO"
                },
                "total_paginas": {
                    "type": "integer"
                },
                "total_registros": {
                    "type": "integer"
                }
            }
        },
        "domain.PaginaProductosDTO": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductoDTO"
                    }
                },
                "limite": {
                    "type": "integer"
                },
                "pagina_actual": {
                    "type": "integer"
                },
                "paginacion": {
                    "$ref": "#/definitions/domain.MetadatosPaginacionDTO"
                },
                "total_paginas": {
                    "type": "integer"
                },
                "total_registros": {
                    "type": "integer"
                }
            }
        },
        "domain.PerfilUsuarioDTO": {
            "type": "object",
            "properties": {
                "correo": {
                    "type": "string"
                },
                "direccion": {
                    "type": "string"
                },
                "esta_activo": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mensaje": {
                    "type": "string"
                },
                "nombre_completo": {
                    "type": "string"
                },
                "rol": {
                    "type": "string"
                },
                "telefono": {
                    "type": "string"
                }
            }
        },
        "domain.ProductoAdminDTO": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "en_oferta": {
                    "type": "boolean"
                },
                "en_stock": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "marca": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "precio_normal": {
                    "type": "integer"
                },
                "precio_oferta": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                },
                "sucursal_id": {
                    "type": "integer"
                },
                "supermercado": {
                    "type": "string"
                },
                "ultima_extraccion_el": {
                    "type": "string"
                },
                "unidad": {
                    "type": "string"
                },
                "url_imagen": {
                    "type": "string"
                }
            }
        },
        "domain.ProductoDTO": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "en_oferta": {
                    "type": "boolean"
                },
                "en_stock": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "marca": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "precio": {
                    "type": "number"
                },
                "precio_normal": {
                    "type": "number"
                },
                "precio_oferta": {
                    "type": "number"
                },
                "supermercado": {
                    "type": "string"
                },
                "unidad": {
                    "type": "string"
                },
                "url_imagen": {
                    "type": "string"
                }
            }
        },
        "domain.ProductoDetalleDTO": {
            "type": "object",
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "en_oferta": {
                    "type": "boolean"
                },
                "en_stock": {
                    "type": "boolean"
                },
                "historial": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.HistorialPrecioDTO"
                    }
                },
                "id": {
                    "type": "string"
                },
                "marca": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "precio": {
                    "type": "number"
                },
                "precio_normal": {
                    "type": "number"
                },
                "precio_oferta": {
                    "type": "number"
                },
                "supermercado": {
                    "type": "string"
                },
                "unidad": {
                    "type": "string"
                },
                "url_imagen": {
                    "type": "string"
                }
            }
        },
        "domain.ProductoScrapeadoDTO": {
            "type": "object",
            "required": [
                "precio_normal",
                "producto",
                "sku"
            ],
            "properties": {
                "categoria": {
                    "type": "string"
                },
                "ean_gtin": {
                    "type": "string"
                },
                "en_stock": {
                    "type": "boolean"
                },
                "formato_crudo": {
                    "type": "string"
                },
                "imagen": {
                    "type": "string"
                },
                "marca": {
                    "type": "string"
                },
                "mecanica_promocion": {
                    "type": "string"
                },
                "metrica_unidad": {
                    "type": "string"
                },
                "precio": {
                    "type": "number"
                },
                "precio_normal": {
                    "type": "number"
                },
                "precio_oferta": {
                    "type": "number"
                },
                "precio_por_unidad": {
                    "type": "number"
                },
                "precio_tarjeta": {
                    "type": "number"
                },
                "producto": {
                    "type": "string"
                },
                "sku": {
                    "type": "string"
                },
                "url_imagen": {
                    "type": "string"
                },
                "url_producto": {
                    "type": "string"
                }
            }
        },
        "domain.TrabajoScraperDTO": {
            "type": "object",
            "properties": {
                "cadena_id": {
                    "type": "integer"
                },
                "cadena_nombre": {
                    "type": "string"
                },
                "duracion_segundos": {
                    "type": "number"
                },
                "elementos_extraidos": {
                    "type": "integer"
                },
                "estado": {
                    "type": "string"
                },
                "finalizado_el": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "iniciado_el": {
                    "type": "string"
                },
                "registro_errores": {
                    "type": "string"
                }
            }
        },
        "handlers.GoogleLoginRequest": {
            "type": "object",
            "required": [
                "id_token"
            ],
            "properties": {
                "id_token": {
                    "type": "string"
                }
            }
        },
        "handlers.LoginRequest": {
            "type": "object",
            "required": [
                "correo",
                "password"
            ],
            "properties": {
                "correo": {
                    "type": "string",
                    "example": "usuario.test@uct.cl"
                },
                "password": {
                    "type": "string",
                    "example": "PasswordSegura123!"
                }
            }
        },
        "handlers.LoginResponse": {
            "type": "object",
            "properties": {
                "correo": {
                    "type": "string",
                    "example": "usuario.test@uct.cl"
                },
                "esta_activo": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"
                },
                "mensaje": {
                    "type": "string",
                    "example": "Inicio de sesión exitoso."
                },
                "nombre_completo": {
                    "type": "string",
                    "example": "Vicente Matu"
                },
                "rol": {
                    "type": "string",
                    "example": "registrado"
                },
                "url_avatar": {
                    "type": "string",
                    "example": "https://ejemplo.com/avatar.jpg"
                }
            }
        },
        "handlers.RegistroRequest": {
            "type": "object",
            "required": [
                "correo",
                "nombre_completo",
                "password"
            ],
            "properties": {
                "correo": {
                    "type": "string",
                    "example": "usuario.test@uct.cl"
                },
                "nombre_completo": {
                    "type": "string",
                    "example": "Vicente Matu"
                },
                "password": {
                    "type": "string",
                    "example": "PasswordSegura123!"
                }
            }
        },
        "handlers.RegistroResponse": {
            "type": "object",
            "properties": {
                "correo": {
                    "type": "string",
                    "example": "usuario.test@uct.cl"
                },
                "esta_activo": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"
                },
                "mensaje": {
                    "type": "string",
                    "example": "Usuario registrado con éxito. Se requiere confirmar el correo electrónico antes de iniciar sesión."
                },
                "nombre_completo": {
                    "type": "string",
                    "example": "Vicente Matu"
                },
                "rol": {
                    "type": "string",
                    "example": "registrado"
                },
                "token_verificacion": {
                    "type": "string",
                    "example": "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
                }
            }
        },
        "handlers.ejecutarScraperRequest": {
            "type": "object",
            "properties": {
                "producto_id": {
                    "type": "string"
                },
                "producto_url": {
                    "type": "string"
                },
                "spider": {
                    "type": "string"
                }
            }
        },
        "middleware.RespuestaError": {
            "type": "object",
            "properties": {
                "detalle": {
                    "description": "Información técnica u origen del error",
                    "type": "string"
                },
                "estado": {
                    "description": "Código numérico del estado HTTP (400, 404, 500, etc.)",
                    "type": "integer"
                },
                "mensaje": {
                    "description": "Mensaje descriptivo amigable para el cliente",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Gateway de Supermercados",
	Description:      "API Gateway construida en Go con Gin",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
