basePath: /
host: localhost:8080
info:
  contact: {}
  description: API Gateway construida en Go con Gin
  title: API Gateway de Supermercados
  version: "1.0"
paths:
  /:
    get:
      description: Endpoint raíz para comprobar el estado de la API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Muestra mensaje de bienvenida
      tags:
      - root
swagger: "2.0"
