apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        args:
        - clone
        - --single-branch
        - --branch=develop
        - https://github.com/danirc2024/Taller_integracion_III.git
        - /app
        volumeMounts:
        - name: app-code
          mountPath: /app
      containers:
      - name: bot
        image: golang:alpine
        workingDir: /app/backend/bot_discord
        command: ["/bin/sh", "-c"]
        args: ["apk add --no-cache git && go run ."]
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: token
        - name: DISCORD_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: channel_id
        - name: SCRAPER_API_BASE_URL
          value: "http://api:8080/api/v1/scraper/trabajos"
        volumeMounts:
        - name: app-code
          mountPath: /app
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
      volumes:
      - name: app-code
        emptyDir: {}
