apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  labels:
    app: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: ghcr.io/danirc2024/taller_integracion_iii-scraper:develop
        imagePullPolicy: Always
        env:
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: SCRAPER_API_URL
          value: "http://api:8080/api/v1/scraper/productos"
        command: ["python", "-m", "scraper_core.worker"]
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
