apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scraper
  name: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - command:
        - python
        - -m
        - scraper_core.worker
        env:
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: db-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: db-secret
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: db-secret
        - name: REDIS_URL
          value: redis://redis:6379/0
        - name: SCRAPER_API_URL
          value: http://api:8080/api/v1/scraper/productos
        image: ghcr.io/danirc2024/taller_integracion_iii-scraper:develop
        imagePullPolicy: Always
        name: scraper
        resources:
          limits:
            cpu: 350m
          requests:
            cpu: 50m
            memory: 64Mi
