apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ghcr.io/danirc2024/taller_integracion_iii-frontend:develop
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 350m
          requests:
            cpu: 30m
            memory: 64Mi
