apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ghcr.io/danirc2024/taller_integracion_iii-frontend:develop
        imagePullPolicy: Always
        name: frontend
        env:
        - name: VITE_API_URL
          value: "https://api-vmatus.dev.censei.cl/api/v1"
        - name: VITE_IA_URL
          value: "https://api-vmatus.dev.censei.cl/api/v1" # IA usa el mismo API Gateway en el cluster
        - name: VITE_GOOGLE_CLIENT_ID
          value: "AQUI_VA_EL_CLIENT_ID_DE_GOOGLE"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 30m
            memory: 64Mi
