apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/danirc2024/taller_integracion_iii-frontend:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 15Mi
            cpu: 30m
          limits:
            memory: 50Mi
            cpu: 100m
