apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rutahorro-ingress
  labels:
    app: rutahorro
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/target: "proxy.inf.uct.cl"
spec:
  rules:
    - host: api-vmatus.dev.censei.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080
    - host: miweb-vmatus.dev.censei.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
